// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqgsidfxlxnlgvyeupye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZ3NpZGZ4bHhubGd2eWV1cHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTMzNjAsImV4cCI6MjA1Nzk4OTM2MH0.yhKDoG4tc9M-Q7NXIdRkCwb8rkOj9FGyzpVCnbeKGm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);